version: 2

sources:
  - name: crm
    database: "{{ target.database }}"
    schema: RAW_CRM
    tables:
      - name: customers
      - name: sales_reps
      - name: opportunities
      - name: orders
        config:
          loaded_at_field: ingested_at
          freshness:
            warn_after:
              count: 24
              period: hour
            error_after:
              count: 48
              period: hour     

  - name: hr
    database: "{{ target.database }}"
    schema: RAW_HR
    tables:
      - name: employees
      - name: departments